language: bash

env:
  global:
  - IMAGE_NAME=${DOCKER_USERNAME}/spark-custom

matrix:
  include:
  # Debian builds
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - HADOOP_VERSION=3.1.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.2
    - HADOOP_VERSION=3.1.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.2
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.1
    - HADOOP_VERSION=3.1.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.1
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.0
    - HADOOP_VERSION=3.1.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.4.0
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.2
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.1
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian
  - services: docker
    env:
    - SPARK_VERSION=2.3.0
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=debian

  # Alpine builds
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - HADOOP_VERSION=3.1.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.2
    - HADOOP_VERSION=3.1.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.2
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.1
    - HADOOP_VERSION=3.1.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.1
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.0
    - HADOOP_VERSION=3.1.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.4.0
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.3
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.2
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.1
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  - services: docker
    env:
    - SPARK_VERSION=2.3.0
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
    - DIST=alpine
  
script:
- docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
- HIVE_TAG_SUFFIX=$(if [ "${WITH_HIVE}" = "true" ]; then echo _hive; fi)
- PYSPARK_TAG_SUFFIX=$(if [ "${WITH_PYSPARK}" = "true" ]; then echo _pyspark; fi)
- TAG_NAME=${SPARK_VERSION}_hadoop-${HADOOP_VERSION}${HIVE_TAG_SUFFIX}${PYSPARK_TAG_SUFFIX}_${DIST}
- FULL_IMAGE_NAME="${IMAGE_NAME}:${TAG_NAME}"
- |-
  docker build ${DIST}/ -t ${FULL_IMAGE_NAME} \
    --build-arg SPARK_VERSION=${SPARK_VERSION} \
    --build-arg HADOOP_VERSION=${HADOOP_VERSION} \
    --build-arg WITH_HIVE=${WITH_HIVE} \
    --build-arg WITH_PYSPARK=${WITH_PYSPARK} \
    ;
# Just push, doesn't matter if it's TRAVIS_PULL_REQUEST false/true
- docker push ${FULL_IMAGE_NAME};

branches:
  only:
  - master
