version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout

    # login to Docker first
    - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    
    # build the application image
    - run: docker build . -t guangie88/spark-custom:2.3.2_hadoop-3.2.0

    # push the application image
    - run: docker tag guangie88/spark-custom:2.3.2_hadoop-3.2.0 guangie88/test-spark-custom:2.3.2_hadoop-3.2.0
    - run: docker push guangie88/test-spark-custom:2.3.2_hadoop-3.2.0
